spring:
  data:
    mongodb:
      database: springangular
      host: localhost
      port: 27017
  devtools:
      restart:
        poll-interval:
  profiles:
    active: test

server:
  port: 7890
  servlet:
    path:  /

